language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
#
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - createuser --createdb --createrole --echo --login --username=postgres dimcaluser
# command to run tests
script: cd src/dimcal && ./manage.py test
