---
language: python
python:
  - "3.5"
sudo: false
# command to install dependencies
install: "pip install -r requirements.txt"
#
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - createuser --createdb --createrole --echo --login --username=postgres dimcaluser
# command to run tests
script: cd src/dimcal && ./manage.py test -v 2
#
before_deploy:
  - cd ../../wget_build && ./build_static.sh && echo `pwd` && ls -lR
#
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "dimcalendar.gregnicol.xyz"
  local_dir:   ${TRAVIS_BUILD_DIR}/wget_build/
  skip_cleanup: true
  region: "eu-central-1"
