---
language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
#
addons:
  postgresql: "9.4"
sudo: false
services:
  - postgresql
before_script:
  - createuser --createdb --createrole --echo --login --username=postgres dimcaluser
# command to run tests
script: cd src/dimcal && ./manage.py test -v 2
#
before_deploy:
  - cd ../../build/ && ./build.sh
#
deploy:
  on:
    branch: s3deploy
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "dimcalendar.gregnicol.xyz"
  local_dir:   ${TRAVIS_BUILD_DIR}/build/html/
  skip_cleanup: true
  region: "eu-central-1"
  detect_encoding: true
  cache_control: "max-age=3600"

deploy:
  provider: releases
  api_key:
    secure: 1J9/zQ4XuYfO22YF+iKVZMxfOb0sJr7ZmBzH8Ynrc6+9a0HL8PxnuWcwL01S2wPKHVvwjHbTfihLFquZ1PcY/wF8tI51axu6zwbTK5icCXf4vSSRJHvvGcfoYdJmurbCilezoAB2YMPbxTFNjOAXyCy4DKygRQzah+T591YGV2YzQyMTGCqnUnmRrkFF/NQmlHa4UJKnpQzbtBVp2oAIaOVw51gcuOWx4HTkRcmKQCGySBXN1Rpfe9T9IQIEMRTzLG78a7KQBaUMvQvUD0mx1bdPruNsa6MDCJhjGTQgRpi5I+xifvtulIzqJhZwGNgER4RWapDU96HzCQHghuItRPIzkds8p/AMo8TpIzwiEK7tJqzs1JHeEGTAFqTX/esJZj/M4VQAu4s8aiZAD4RQD+beE/DMRN2jvHp+EUC8WzbpuxYrSLeYuhrhD7YOwNLRPyUjLbapb7+1A0pxra5mwp/qEEx9L7u3By9P2KKYSAgGH264VnCJI82nCeZ60I0woFh+RXoTygrgyfFIYwl3IhElPEndddk4IhmHNLda/oemIMwVlI46RrVXGEJUQVRFg0UaOxONexvQDtU2qV8Q3JeGS/NhSGTYQGs9zE39WTK1DoQk6Ho/xlRgj0kE04+cHiSX2LIFK77XaRMicSMDSJQbxukppXQ5JkyUW/9/wMk=
    file: /home/travis/build/gregn610/dimcal/build/sql/build/dim_calendar.plpgsql.tar.gz
  overwrite: true
  skip_cleanup: true
  on:
    repo: gregn610/dimcal
    branch: s3deploy
