language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
#
services:
  - postgresql
#before_script:
#  - psql -c 'create database dimcaltestdatabase;' -U postgres
# command to run tests
script: cd src/dimcal && ./manage.py test
