---
language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: false
# command to install dependencies
install: "pip install -r requirements.txt"
#
addons:
  postgresql: "9.5"
sudo: required
services:
  - postgresql
before_script:
  - createuser --createdb --createrole --echo --login --username=postgres dimcaluser
# command to run tests
script: cd src/dimcal && ./manage.py test -v 3 --debug-sql
##
#after_success:
#  - cd src/dimcal && ./manage.py runserver
##
#deploy:
#  provider: s3
#  access_key_id: "YOUR AWS ACCESS KEY"
#  secret_access_key: "YOUR AWS SECRET KEY"
#  bucket: "dimcalendar.gregnicol.xyz"
#  local_dir: wget_build/localhost:8000/
#  skip_cleanup: true
#  region: "eu-central-1"
