---
language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
#
addons:
  postgresql: "9.4"
sudo: false
services:
  - postgresql
before_script:
  - createuser --createdb --createrole --echo --login --username=postgres dimcaluser
  - createuser --createdb --createrole --echo --login --username=postgres releaseuser
# command to run tests
script: cd src/dimcal && ./manage.py test -v 2 --settings=dimcal.testsettings.postgresql
#
before_deploy:
  - cd ${TRAVIS_BUILD_DIR}/build/ && ./build.sh
#
#deploy:
# Now on separate branches
