---
language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
#
addons:
  postgresql: "9.4"
sudo: false
services:
  - postgresql
before_script:
  - createuser --createdb --createrole --echo --login --username=postgres dimcaluser
# command to run tests
script: cd src/dimcal && ./manage.py test -v 2
#
before_deploy:
  - cd ../../build/ && ./build.sh
#
deploy:
  on:
    branch: s3deploy
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "dimcalendar.gregnicol.xyz"
  local_dir:   ${TRAVIS_BUILD_DIR}/build/html/
  skip_cleanup: true
  region: "eu-central-1"
  detect_encoding: true
  cache_control: "max-age=3600"

deploy:
  provider: releases
  api_key:
    secure: 15H2qKqMpCVuyYQltAVqaj6qzR6xxyiCuECRMI16/Ojy38LZLUwRlXKxXaPt6zR10jWzKLIjQxMsgAJJ4oGKHUiP17O7pEzXyg04g3sLtNTxBlLctQQka9MPJ6Q/uN2GPRtDrGfJk2t8/ThnKdV/eLDs7qLDbBeJU5lL/MIhAyrdOu9bZp4Z6iHmxpTjCYb9oX37LoJOwbjwB8KzoOs3lhKs1ul3ivc9/buaLgOEgohqwgyukCh1lTCgjdDAbwueHre83q0gImqwpeb0JljKffZ8zFgU162QYDJ7BxmQuaoCLwwpSNzAYBH1nsOvIK1SQJWQXKaJK9pIB/k8+kmaYkNEARkzezw1JAfv9OT19wnydhn7P0Egg+IXEgXVwXaikK22I0bSUAcKCcVO2n/DGn1IA3MCC0IdzZonQ5L8QMTCOBrTb4feRDtCYZLZMrAbSQkA7KTJWrqmyeqgX6v2cOlwVAdV+leh49sBP81rG9hpyDtm1dA9WyBnKnQF7/V84TNPH3pWjBbSI3gzeFYXDpfqMvXrxNqZssvVZbUVALFS0QY99tp2XHCYqKP+W9beTxr65PsJzpd+WyTHfz7eBNgdQ57jO/PdFFznJKlGLOewN5v+nL6auQGGCnur1tFA0i7lyNDTFM/8MgYJ1oR2A2R7JoyOvPgagomR7vqzk2o=
    file: /home/travis/build/gregn610/dimcal/build/sql/build/dim_calendar.plpgsql.tar.gz
  overwrite: true
  skip_cleanup: true
  on:
    repo: gregn610/dimcal
    branch: s3deploy
