---
language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
#
addons:
  postgresql: "9.4"
sudo: false
services:
  - postgresql
before_script:
  - createuser --createdb --createrole --echo --login --username=postgres dimcaluser
  - createuser --createdb --createrole --echo --login --username=postgres releaseuser
# command to run tests
script: cd src/dimcal && ./manage.py test -v 2 --settings=dimcal.testsettings.postgresql
#
before_deploy:
  - cd ${TRAVIS_BUILD_DIR}/build/ && ./build.sh
#
deploy:
  - provider: s3
    on:
      repo: gregn610/dimcal
      branch: s3deploy  
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "dimcalendar.gregnicol.xyz"
    local_dir:   ${TRAVIS_BUILD_DIR}/build/html/
    skip_cleanup: true
    region: "eu-central-1"
    detect_encoding: true
    cache_control: "max-age=3600"

